### ISSUE TITLE
Issue with Downloading 'magicpod-api-client.zip' Using GitHub Actions

### ISSUE THREAD

**Issue by ykws** [Magic-Pod/magicpod-api-client#15]
While the automated download via GitHub Actions has been unsuccessful, we have ascertained that manual download is possible using terminal commands on a Mac. Consequently, we believe that the MAGICPOD_API_TOKEN is configured correctly.

Do you have any insights into what might be causing this issue, and can you confirm whether direct downloading from the [releases](https://github.com/Magic-Pod/magicpod-api-client/releases) is our only option under the circumstances?

### references

🔖 [一括テスト実行・コマンドラインテスト実行](https://support.magic-pod.com/hc/ja/articles/4408903744409-%E4%B8%80%E6%8B%AC%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E8%A1%8C-%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E8%A1%8C)

# Environments

## GitHub Actions

```
OS=linux # Windowsマシン上でのビルドの場合はwindows、Linuxはlinuxを指定
FILENAME=magicpod-api-client # 任意のファイル名
curl -L "https://app.magicpod.com/api/v1.0/magicpod-clients/api/${OS}/latest/" -H "Authorization: Token ${MAGICPOD_API_TOKEN}" --output ${FILENAME}.zip
unzip -o ${FILENAME}.zip
```

### references

🔖 [GitHub Actionsとの連携(モバイルアプリテスト) > 2.シェルスクリプトを作成](https://support.magic-pod.com/hc/ja/articles/18450503007001-GitHub-Actions%E3%81%A8%E3%81%AE%E9%80%A3%E6%90%BA-%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E3%82%A2%E3%83%97%E3%83%AA%E3%83%86%E3%82%B9%E3%83%88-#h_01H256KECHBD4CW89YB0H1MCPE)

## Log

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    59  100    59    0     0    101      0 --:--:-- --:--:-- --:--:--   101
magicpod-api-client.zip
[magicpod-api-client.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of magicpod-api-client.zip or
        magicpod-api-client.zip.zip, and cannot find magicpod-api-client.zip.ZIP, period.
```

**Comment by nkns165** [comment]
Thank you for your question. I'm a developer in MagicPod.

```
    # ステップ8(作成したアプリをMagicPodにアップロードし一括実行する)
      - name: Batch run test
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGIC_POD_API_TOKEN }}  # GitHubで設定した変数名
        run: bash run_magicpod_test.sh  # 先ほど作成したシェルスクリプト
```

I guess the example step above was the culprit, because it said `secrets.MAGIC_POD_API_TOKEN` on the help page while it says `MAGICPOD_API_TOKEN` while creating the secret (I have fixed the document right now).

If it matches your situation, could you try tweaking the secret's name in the step?

**Comment by nkns165** [comment]
Looking at the reactions, I assume we can close this issue for now.
Please reopen if you still have any problems.

**Comment by ykws** [comment]
Thank you for your assistance. However, we are still experiencing issues with downloading the magicpod-api-client. In response to this, we prefer to directly download and use it.

**Comment by nkns165** [comment]
Sorry for that. Of course downloading directly is OK.
If you like, we can support you here, or you can ask our CS team by sending an inquiry within MagicPod.
